
-- Auxiliar de Cozinha (parte 1)
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Pão', 'un', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Pão Australiano', 'un', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Bag catchup heinz', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Bag mostarda', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Catchup sachê heinz', 'cx', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Mostarda sache', 'cx', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Maionese verde', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Maionese de alho', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Cebola Caramelizada', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Cebola Crispy', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Barbecue', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Geleia de pimenta', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Picles', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Costela desfiada (pronta)', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Molho cheddar', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Ovo', 'un', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Sal', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Farinha panko', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Farinha de trigo', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Açucar mascavo', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Amido de Milho', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Pimenta calabresa', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Páprica picante', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Pimenta do reino', 'kg', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO products (category_id, name, unit, minimum_stock, created_at, updated_at) SELECT (SELECT id FROM categories WHERE name = 'Auxiliar de Cozinha'), 'Peper lemon', 'lt', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
